blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/rtl-airband/RTLSDR-Airband/discussions/categories/q-a
    about: Please ask and answer questions here.
